### ISSUE TITLE
LuckPerms for folia

### ISSUE THREAD

**Issue by GarryCZ** [wildmaster84/PlayerHousingAPI#1]
Hi, somehow I can't find "LuckPerms" for folia server anywhere, your github download link is no longer valid (404 not found).
Could you please help me?
Thank you

[12:58:14 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/PlayerHousing-2.8-DEV.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [LuckPerms]. Please download and install these plugins to run 'PlayerHousing'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:511) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by wildmaster84** [comment]
This has been fixed in version 2.8.3 https://github.com/wildmaster84/PlayerHousing/tree/1.21.4
